---
- name: Execute basic commands on target hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Test SSH connectivity with verbose output
      ping:
      register: ping_result
      ignore_errors: yes

    - name: Display ping result
      debug:
        var: ping_result
        verbosity: 0

    # - name: Run uname -a
    #   command: uname -a
    #   register: uname_output

    # - name: Display system information
    #   debug:
    #     var: uname_output.stdout

    # - name: Get process list
    #   command: ps aux
    #   register: process_list

    # - name: Display process list
    #   debug:
    #     var: process_list.stdout_lines
