---
- name: Execute basic commands on target hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Install required Python packages
      raw: |
        sudo apt-get update && \
        sudo apt-get install -y python3-future python3-setuptools && \
        sudo pip3 install 'typing-extensions>=3.7.4' 'future>=0.18.2'
      ignore_errors: yes

    - name: Test SSH connectivity with simple command
      raw: "python3 -c 'print(\"hello\")'"
      register: test_result

    - name: Display test result
      debug:
        var: test_result

    # - name: Run uname -a
    #   command: uname -a
    #   register: uname_output

    # - name: Display system information
    #   debug:
    #     var: uname_output.stdout

    # - name: Get process list
    #   command: ps aux
    #   register: process_list

    # - name: Display process list
    #   debug:
    #     var: process_list.stdout_lines
