name: Execute Ansible Playbook

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: 'Inventory file from inventories folder (e.g. local.ini)'
        required: true
        type: string
        default: 'azure.ini'
      playbook:
        description: 'Playbook file from playbooks folder (e.g. hello-world.yml)'
        required: true
        type: string
        default: 'linux-basic.yml'
      azure_keyvault_name:
        required: true
        type: string
        description: 'Name of the Azure Key Vault to use'
        default: 'ansible-demo-keyvault'
      key_secret_name:
        required: true
        type: string
        description: 'Name of the SSH private key secret in Azure Key Vault'
        default: 'ansible-ssh-private-key'


jobs:
  call-ansible-workflow:
    uses: ./.github/workflows/ansible.yml
    with:
      environment: demo
      inventory_file: inventories/${{ inputs.inventory }}
      playbook_file: playbooks/${{ inputs.playbook }}
      azure_keyvault_name: ${{ inputs.azure_keyvault_name }}
      key_secret_name: ${{ inputs.key_secret_name }}
    secrets: inherit
