name: Reusable Ansible Workflow

on:
  workflow_call:
    inputs:
      inventory_file:
        required: true
        type: string
        description: 'Path to the Ansible inventory file'
      playbook_file:
        required: true
        type: string
        description: 'Path to the Ansible playbook file'
      environment:
        required: true
        type: string
        description: 'Environment to deploy (e.g., dev, staging, prod)'
      ansible_args:
        required: false
        type: string
        description: 'Additional Ansible arguments'
        default: ''

jobs:
  run-ansible:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Files
        run: |
          if [ ! -f "${{ inputs.inventory_file }}" ]; then
            echo "Error: Inventory file '${{ inputs.inventory_file }}' not found"
            exit 1
          fi
          
          if [ ! -f "${{ inputs.playbook_file }}" ]; then
            echo "Error: Playbook file '${{ inputs.playbook_file }}' not found"
            exit 1
          fi

      - name: Azure Login
        uses: azure/login@v2
        with:
            creds: ${{ secrets.ARM_SERVICE_PRINCIPAL_CREDS }}
            
      - name: Run Ansible Playbook
        env:
            AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            AZURE_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            AZURE_TENANT: ${{ secrets.ARM_TENANT_ID }}
        run: |
          ansible-playbook \
            -i ${{ inputs.inventory_file }} \
            ${{ inputs.playbook_file }} \
            ${{ inputs.ansible_args }}
