name: Execute Ansible Playbook

on:
  workflow_dispatch:
    inputs:
      inventory:
        description: 'Inventory file from inventories folder (e.g. local.ini)'
        required: true
        type: string
        default: 'azure.ini'
      playbook:
        description: 'Playbook file from playbooks folder (e.g. hello-world.yml)'
        required: true
        type: string
        default: 'linux-basic.yml'

jobs:
  call-ansible-workflow:
    uses: ./.github/workflows/ansible.yml
    with:
      inventory_file: inventories/${{ inputs.inventory }}
      playbook_file: playbooks/${{ inputs.playbook }}
    secrets: inherit
