name: Ansible Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ansible-hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Create inventory file
        run: |
          echo "localhost ansible_connection=local" > inventory.ini
          
      - name: Create Ansible playbook
        run: |
          cat << EOF > hello-world.yml
          ---
          - name: Hello World Playbook
            hosts: localhost
            gather_facts: false
            tasks:
              - name: Print hello world
                debug:
                  msg: "Hello, World from Ansible!"
          EOF
          
      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.ini hello-world.yml
