name: 'IaC-Azure - Vault Setup'

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Apply the Terraform changes'
        type: boolean
        default: false
        required: true
      destroy:
        description: 'Destroy the infrastructure'
        type: boolean
        default: false
        required: true

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      working_directory: infrastructure/azure/vault_setup
      environment: demo
      apply: ${{ inputs.apply }}
      destroy: ${{ inputs.destroy }}
    secrets: inherit
